#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.bittrex.com/api/v1.1/public/getticker?market=BTC-REP")
rep_btc=$(jshon <<<"$json" -e result -e Last -u)
rep_btc=$(printf "%.10f" "$rep_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$rep_btc * $btc_usd" | awk '{printf "%.10f", $0}'