#!/usr/bin/env bash
set -e
pair=xrpusd
sources=(
  binance
  bitfinex
  hitbtc
  huobi
  kraken
  okex
)

case $1 in
  bitfinex) {
    setzer x-price "$1" xrp:usd
  };;
  kraken) {
    setzer x-price "$1" xxrp:zusd
  };;
  huobi|binance|okex) {
    xrp_usdt=$(setzer x-price "$1" xrp:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l<<<"$xrp_usdt * $usdt_usd")"
  };;
  hitbtc) {
    xrp_btc=$(setzer x-price "$1" xrp:btc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$xrp_btc * $btc_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
