#!/usr/bin/env bash
set -e
pair=bnbusd
sources=(
  binance
  gateio
  hitbtc
)

case $1 in
  binance) {
    bnb_usdt=$(setzer x-price $1 btc:usdc)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format $(bc -l <<<"$bnb_usdt * $usdt_usd")
  };;
  gateio) {
    bnb_btc=$(setzer x-price $1 bnbbtc)
    btc_usd=$(setzer price btcusd)
    setzer --format $(bc -l <<<"$bnb_btc * $btc_usd")
  };;
  hitbtc) {
    setzer x-price $1 $pair
  };;
  ls) {
    for src in ${sources[@]}; do
      echo "$src: $(setzer price $pair $src)"
    done
  };;
  sources) {
    printf "%s\n" ${sources[@]}
  };;
  median|*) {
    setzer --median $pair 2 ${sources[@]}
  };;
esac
