#!/usr/bin/env bash
set -e
pair=usdc:usd
sources=(
  binance
  coinbase
  poloniex
)

case $1 in
  binance|coinbase|poloniex) {
    btc_usdc=$(setzer x-price "$1" btc:usdc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$btc_usd / $btc_usdc")"
  };;
  *) {
    export SETZER_MIN_MEDIAN=2
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
