#!/usr/bin/env bash
set -e
pair=btcusd
sources=(
  bitstamp
  bittrex
  coinbase
  gemini
  kraken
)

case $1 in
  bitstamp|bittrex|coinbase|gemini) {
    setzer x-price "$1" $pair
  };;
  kraken) {
    setzer x-price kraken xxbt:zusd
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
