#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.bibox.com/v1/mdata?cmd=ticker&pair=MKR_ETH")
mkr_eth=$(jshon <<<"$json" -e result -e last -u)
mkr_eth=$(printf "%.10f" "$mkr_eth")
eth_usd=$(setzer price eth)
bc -l <<<"$mkr_eth * $eth_usd" | awk '{printf "%.10f", $0}'