#!/usr/bin/env bash
set -e
json=$(curl -sS "https://poloniex.com/public?command=returnTicker")
rep_btc=$(jshon <<<"$json" -e BTC_REP -e last -u)
rep_btc=$(printf "%.10f" "$rep_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$rep_btc * $btc_usd" | awk '{printf "%.10f", $0}'