#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.bitfinex.com/v2/ticker/tMKRBTC")
mkr_btc=$(jshon <<<"$json" -e 6)
mkr_btc=$(printf "%.10f" "$mkr_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$mkr_btc * $btc_usd" | awk '{printf "%.10f", $0}'