#!/usr/bin/env bash
set -e
pair=ethbtc
sources=(
  binance
  bitfinex
  coinbase
  huobi
  kraken
  poloniex
)

case $1 in
  binance|bitfinex|coinbase|huobi|poloniex) {
    setzer x-price "$1" ethbtc
  };;
  kraken) {
    setzer x-price kraken xeth:xxbt 
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
