#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.gdax.com/products/BTC-USDC/ticker")
price=$(jshon <<<"$json" -e price -u)
#todo replace with 'setzer price btcusd'
json=$(curl -sS "https://api.coinmarketcap.com/v2/ticker/1/")
btc=$(jshon <<<"$json" -e data -e quotes -e USD -e price -u)
bc -l <<<"$price / $btc"