#!/usr/bin/env bash
set -e
pair=dgxusd
sources=(
  bitfinex
  kyber
)

case $1 in
  bitfinex) {
    dgx_usdt=$(setzer x-price "$1" dgxusd)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format "$(bc -l <<<"$dgx_usdt * $usdt_usd")"
  };;
  kyber) {
    json=$(curl -sS "https://api.kyber.network/buy_rate?id=0x4f3afec4e5a3f2a6a1a411def7d7dfe50ee057bf&qty=2.5")
    eth=$(jshon <<<"$json" -e data -e 0 -e src_qty -e 0 -u)
    dgx=$(jshon <<<"$json" -e data -e 0 -e dst_qty -e 0 -u)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$eth / $dgx * $eth_usd")"
  };;
  *) {
    export SETZER_MIN_MEDIAN=2
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
