#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=BCHABCBTC")
zrx_btc=$(jshon <<<"$json" -e price -u)
zrx_btc=$(printf "%.10f" "$zrx_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$zrx_btc * $btc_usd" | awk '{printf "%.10f", $0}'