#!/usr/bin/env bash
set -e
pair=dgdusd
sources=(
  binance
  huobi
)

case $1 in
  binance|huobi) {
    dgd_btc=$(setzer x-price "$1" dgdbtc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$dgd_btc * $btc_usd")"
  };;
  ls) {
    for src in "${sources[@]}"; do
      echo "$src: $(setzer price "$pair" "$src")"
    done
  };;
  sources) {
    printf "%s\n" "${sources[@]}"
  };;
  median|*) {
    export SETZER_MIN_MEDIAN=2
    setzer --median $pair "${sources[@]}"
  };;
esac
