#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=MANABTC")
mana_btc=$(jshon <<<"$json" -e price -u)
mana_btc=$(printf "%.10f" "$mana_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$mana_btc * $btc_usd" | awk '{printf "%.10f", $0}'