#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.okex.com/api/v1/ticker.do?symbol=mkr_eth")
mkr_eth=$(jshon <<<"$json" -e ticker -e last -u)
mkr_eth=$(printf "%.10f" "$mkr_eth")
eth_usd=$(setzer price eth)
bc -l <<<"$mkr_eth * $eth_usd" | awk '{printf "%.10f", $0}'