#!/usr/bin/env bash
set -e
src=$1
pair=${2/:/}

latestBlock=$(setzer --eth-blocknumber)

blocks=(
  $(bc -l <<<"obase=16; ibase=16; $latestBlock")
  $(bc -l <<<"obase=16; ibase=16; $latestBlock-10")
  $(bc -l <<<"obase=16; ibase=16; $latestBlock-20")
)

total=0;
count=0;
for block in ${blocks[@]}
do
  price=$(ETH_BLOCK=0x$block setzer x-price $1 $2)
  total=$(bc -l <<<"$total+$price")
  ((count+=1))
done
setzer --format $(bc -l <<<"$total/$count")


