#!/usr/bin/env bash
set -e
pair=ethusd
sources=(
  binance
  bitfinex
  bitstamp
  coinbase
  ftx
  gemini
  kraken
)

case $1 in
  binance) {
    eth_btc=$(setzer x-price "$1" ethbtc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$eth_btc * $btc_usd")"
  };;
  bitfinex) {
    eth_usdt=$(setzer x-price "$1" "$pair")
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$eth_usdt * $usdt_usd")"
  };;
  bitstamp|coinbase|ftx|gemini) {
    setzer x-price "$1" "$pair"
  };;
  kraken) {
    setzer x-price kraken xeth:zusd
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
