#!/usr/bin/env bash
set -e
pair=mkrusd
sources=(
  bitfinex
  hitbtc
  kyber
  okex
)

case $1 in
  bitfinex) {
    mkr_eth=$(setzer x-price "$1" mkr:eth)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$mkr_eth * $eth_usd")"
  };;
  hitbtc) {
    mkr_btc=$(setzer x-price "$1" mkr:btc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$mkr_btc * $btc_usd")"
  };;
  kyber) {
    mkr_eth=$(setzer x-price "$1" mkr:eth)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$mkr_eth * $eth_usd")"
  };;
  okex) {
    mkr_btc=$(setzer x-price "$1" mkr:btc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$mkr_btc * $btc_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac