#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.bitfinex.com/v2/ticker/tOMGUSD")
price=$(jshon <<<"$json" -e 6)
#todo replace with 'setzer price btcusd'
json=$(curl -sS "https://api.coinmarketcap.com/v2/ticker/825/")
usdt=$(jshon <<<"$json" -e data -e quotes -e USD -e price -u)
bc <<<"$price * $usdt"
