#!/usr/bin/env bash
set -e
pair=usdc:usd
sources=(
  binance
  coinbase
  poloniex
)

case $1 in
  binance|coinbase|poloniex) {
    btc_usdc=$(setzer x-price $1 btc:usdc)
    btc_usd=$(setzer price btcusd)
    setzer --format $(bc -l <<<"$btc_usdc / $btc_usd")
  };;
  ls) {
    for src in ${sources[@]}; do
      echo "$src: $(setzer price $pair $src)"
    done
  };;
  sources) {
    printf "%s\n" ${sources[@]}
  };;
  median|*) {
    setzer --median $pair 2 ${sources[@]}
  };;
esac
