#!/usr/bin/env bash
set -e
pair=compusd
sources=(
  binance
  coinbase
  huobi
  kraken
  kucoin
  uniswap
)

case $1 in
  binance|huobi|kucoin) {
    comp_usdt=$(setzer x-price "$1" comp:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$comp_usdt * $usdt_usd")"
  };;
  coinbase|kraken) {
    setzer x-price "$1" comp:usd
  };;
  uniswap) {
    comp_eth=$(setzer x-price "$1" comp:eth)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$comp_eth * $eth_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac