#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.bitfinex.com/v2/ticker/tETHUSD")
eth_usdt=$(jshon <<<"$json" -e 6)
eth_usdt=$(printf "%.10f" "$eth_usdt")
json=$(curl -sS "https://api.coinmarketcap.com/v2/ticker/825/")
usdt_usd=$(jshon <<<"$json" -e data -e quotes -e USD -e price -u)
usdt_usd=$(printf "%.10f" "$usdt_usd")
bc -l <<<"$eth_usdt * $usdt_usd" | awk '{printf "%.10f", $0}'