#!/usr/bin/env bash
set -e
pair=${1/:/}; shift # e.g. ethusd
sources=( "$@" )    # e.g. binance bitfinex coinbase

mkdir -p "$SETZER_CACHE"
file=$SETZER_CACHE/${pair,,}

get-median () {
  for src in "${sources[@]}"; do
    price=$(timeout "$SETZER_TIMEOUT" setzer price "$pair" "$src" 2> /dev/null || true)
    if [[ $price ]]; then
      if [[ $price =~ ^[+-]?[0-9]+\.?[0-9]*$  ]]; then
        prices+=( "$price" )
      fi
    fi
  done

  if [[ ${#prices[@]} -lt $SETZER_MIN_MEDIAN ]]; then
    echo "Error: not enough sources to provide a median"
    exit 1
  fi

  med=$(tr " " "\\n" <<< "${prices[@]}" | datamash median 1)
  setzer --format "$med" > "$file"
}

[[ ! -e $file ]] && get-median

[ "$(( $(date +"%s") - $(date +"%s" -r "$file") ))" -gt "$SETZER_CACHE_EXPIRY" ] && get-median

cat "$file"
