#!/usr/bin/env bash
set -e
json=$(curl -sS "https://poloniex.com/public?command=returnTicker")
gnt_btc=$(jshon <<<"$json" -e BTC_GNT -e last -u)
gnt_btc=$(printf "%.10f" "$gnt_btc")
btc_usd=$(setzer price btcusd)
bc -l <<<"$gnt_btc * $btc_usd" | awk '{printf "%.10f", $0}'