#!/usr/bin/env bash
set -e
pair=bnbusd
sources=(
  binance
  gateio
  hitbtc
)

case $1 in
  binance) {
    bnb_usdt=$(setzer x-price "$1" bnb:usdc)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format "$(bc -l <<<"$bnb_usdt * $usdt_usd")"
  };;
  gateio) {
    bnb_usdt=$(setzer x-price "$1" bnbusd)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format "$(bc -l <<<"$bnb_usdt * $usdt_usd")"
  };;
  hitbtc) {
    bnb_usdt=$(setzer x-price "$1" bnbusd)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format "$(bc -l <<<"$bnb_usdt * $usdt_usd")"
  };;
  *) {
    export SETZER_MIN_MEDIAN=2
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
