#!/usr/bin/env bash
set -e
pair=ethusd
sources=(
  binance
  bitfinex
  bitstamp
  coinbase
  gemini
  kraken
)

case $1 in
  binance) {
    eth_btc=$(setzer x-price $1 ethbtc)
    btc_usd=$(setzer price btcusd)
    setzer --format $(bc -l <<<"$eth_btc * $btc_usd")
  };;
  bitfinex) {
    eth_usdt=$(setzer x-price $1 $pair)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format $(bc -l <<<"$eth_usdt * $usdt_usd")
  };;
  bitstamp|coinbase|gemini|kraken) {
    setzer x-price $1 $pair
  };;
  median|*) {
    echo $(setzer --median $pair 3 ${sources[@]})
  };;
esac
