#!/usr/bin/env bash
pair=$1; shift

for src in "$@"; do
  price=$(timeout 5 setzer price $pair $src 2> /dev/null || true)
  if [[ $price ]]; then
    if [[ $price =~ ^[+-]?[0-9]+\.?[0-9]*$  ]]; then
      prices+=( "$price" )
    fi
  fi
done

if [[ ${#prices[@]} -lt 3 ]]; then
  echo "Error: not enough sources to provide a median"
  exit 1
fi

med=$(tr " " "\\n" <<< "${prices[@]}" | datamash median 1)
setzer --format $med
