#!/usr/bin/env bash
set -e
pair=lendusd
sources=(
  binance
  kyber
)

case $1 in
  binance) {
    lend_btc=$(setzer x-price "$1" lend:btc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$lend_btc * $btc_usd")"
  };;
  kyber) {
    lend_eth=$(setzer x-price "$1" lend:eth)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$lend_eth * $eth_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
