#!/usr/bin/env bash
set -e
src=$1
pair=${2/:/}

if [[ ${#2} -eq 6 ]]; then
  base=${pair:0:3}
  quote=${pair:3:6}
else
  base=${2%:*}
  quote=${2#*:}
fi

# Setting up base URLs for exchanges
ORIGIN_THEGRAPH_URL="${ORIGIN_THEGRAPH_URL:-https://api.thegraph.com}"
ORIGIN_BINANCE_URL="${ORIGIN_BINANCE_URL:-https://www.binance.com}"
ORIGIN_BITFINEX_URL="${ORIGIN_BITFINEX_URL:-https://api.bitfinex.com}"
ORIGIN_BITSTAMP_URL="${ORIGIN_BITSTAMP_URL:-https://www.bitstamp.net}"
ORIGIN_BITTHUMB_URL="${ORIGIN_BITTHUMB_URL:-https://global-openapi.bithumb.pro}"
ORIGIN_BITTREX_URL="${ORIGIN_BITTREX_URL:-https://api.bittrex.com}"
ORIGIN_CMC_URL="${ORIGIN_CMC_URL:-https://pro-api.coinmarketcap.com}"
ORIGIN_COINBASE_URL="${ORIGIN_COINBASE_URL:-https://api.pro.coinbase.com}"
ORIGIN_CRYPTOCOMPARE_URL="${ORIGIN_CRYPTOCOMPARE_URL:-https://min-api.cryptocompare.com}"
ORIGIN_DDEX_URL="${ORIGIN_DDEX_URL:-https://api.ddex.io}"
ORIGIN_FTX_URL="${ORIGIN_FTX_URL:-https://ftx.com}"
ORIGIN_FX_URL="${ORIGIN_FX_URL:-https://api.exchangeratesapi.io}"
ORIGIN_GATEIO_URL="${ORIGIN_GATEIO_URL:-https://fx-api.gateio.ws}"
ORIGIN_GEMINI_URL="${ORIGIN_GEMINI_URL:-https://api.gemini.com}"
ORIGIN_HITBTC_URL="${ORIGIN_HITBTC_URL:-https://api.hitbtc.com}"
ORIGIN_HUOBI_URL="${ORIGIN_HUOBI_URL:-https://api.huobi.pro}"
ORIGIN_KRAKEN_URL="${ORIGIN_KRAKEN_URL:-https://api.kraken.com}"
ORIGIN_KUCOIN_URL="${ORIGIN_KUCOIN_URL:-https://api.kucoin.com}"
ORIGIN_KYBER_URL="${ORIGIN_KYBER_URL:-https://api.kyber.network}"
ORIGIN_OKEX_URL="${ORIGIN_OKEX_URL:-https://www.okex.com}"
ORIGIN_POLONIEX_URL="${ORIGIN_POLONIEX_URL:-https://poloniex.com}"
ORIGIN_UPBIT_URL="${ORIGIN_UPBIT_URL:-https://api.upbit.com}"

case $src in
  balancer) {
    case "${pair^^}" in
      BALUSD) {
        id="0xba100000625a3754423978a60c9317c58a424e3d"
      };;
      AAVEUSD) {
        id="0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"
      };;
      WNXMUSD) {
        id="0x0d438f3b5175bebc262bf23753c1e53d03432bde"
      };;
    esac
    json=$(curl \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { tokenPrices(where: { id: $id }) { symbol price poolLiquidity } }", "variables": { "id": "'"$id"'" } }' \
      "$ORIGIN_THEGRAPH_URL/subgraphs/name/balancer-labs/balancer")
    setzer --format "$(jshon <<<"$json" -e data -e tokenPrices -e 0 -e price -u)"
  };;
  balancer_v2) {
    ten_to_18=$(printf '%064X' 1000000000000000000) # 10^18 left-padded to 32 bytes
    case "${pair^^}" in
      WSTETHETH) {
        pool_addr=32296969ef14eb0c6d29669c550d4a0449130230 # wstETH/wETH pool, but prices expressed in stETH/ETH
      };;
    esac
    # keccak256("getLatest(uint8)")
    getLatest_method_id=b10be739

    tokenprice=$(setzer \
      --eth-call \
      "$pool_addr" \
      "$getLatest_method_id" \
      "0000000000000000000000000000000000000000000000000000000000000000")  #PAIR_PRICE

    case "${pair^^}" in
      WSTETHETH) {
        # wstETH is a non-rebasing wrapper that exposes the underlying stETH shares
        wsteth_contract_addr=7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        # keccak256("stEthPerToken()")
        steth_per_token_method_id=035faf82
        # how many stETH wei one would receive by unwarpping 10^18 wstETH wei
        steth_per_wsteth=$(setzer --eth-call "$wsteth_contract_addr" "$steth_per_token_method_id")
        # wstethEthPrice = stethPerWsteth * stethEthPrice
        price=$(bc -l <<<"ibase=16; (${steth_per_wsteth^^} / ${ten_to_18^^} * ${tokenprice^} / ${ten_to_18^^})")
      };;
      *) {
        price=$(bc -l <<<"ibase=16; ${tokenprice^^} / ${ten_to_18^^} ")
      };;
    esac
    if [[ -n $price ]]; then
      setzer --format $price
    fi
  };;
  binance) {
    json=$(curl -sS "${ORIGIN_BINANCE_URL}/api/v3/ticker/price?symbol=${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e price -u)"
  };;
  bitfinex) {
    json=$(curl -sS "${ORIGIN_BITFINEX_URL}/v2/ticker/t${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e 6)"
  };;
  bitstamp) {
    json=$(curl -sS "${ORIGIN_BITSTAMP_URL}/api/v2/ticker/${base,,}${quote,,}")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  bitthumb) {
    json=$(curl -sS "${ORIGIN_BITTHUMB_URL}/openapi/v1/spot/ticker?symbol=${base^^}-${quote^^}")
    setzer --format "$(jshon <<<"$json" -e data -e 0 -e c -u)"
  };;
  bittrex) {
    json=$(curl -sS "${ORIGIN_BITTREX_URL}/api/v1.1/public/getticker?market=${quote^^}-${base^^}")
    setzer --format "$(jshon <<<"$json" -e result -e Last -u)"
  };;
  cmc) {
    ticker=$(case "${pair^^}" in
      USDTUSD) { echo "825";  };;
      POLYUSD) { echo "2496"; };;
    esac)
    json=$(curl -sS -H "X-CMC_PRO_API_KEY:  $CMC_API_KEY" -H "Accept: application/json" -d  "id=$ticker" -G ${ORIGIN_CMC_URL}/v1/cryptocurrency/quotes/latest)
    setzer --format "$(jshon <<<"$json" -e data -e "$ticker" -e quote -e USD -e price -u)"
  };;
  coinbase) {
    json=$(curl -sS "${ORIGIN_COINBASE_URL}/products/${base^^}-${quote^^}/ticker")
    setzer --format "$(jshon <<<"$json" -e price -u)"
  };;
  cryptocompare) {
    json=$(curl -sS "${ORIGIN_CRYPTOCOMPARE_URL}/data/price?fsym=${base^^}&tsyms=${quote^^}")
    setzer --format "$(jshon <<<"$json" -e USD -u)"
  };;
  curve) {
    ten_to_18=$(printf '%064X' 1000000000000000000) # 10^18 left-padded to 32 bytes
    case "${pair^^}" in
      WSTETHETH) {
        crv_contract_addr=DC24316b9AE028F1497c275EB9192a3Ea0f67022 # stETH/ETH pool
        crv_src_token=$(printf '%064X' 1) # stETH index
        crv_dst_token=$(printf '%064X' 0) # ETH index
        crv_src_amount=$ten_to_18
      };;
      *) {
        echo >&2 "Error: pair not supported for Curve exchange: $pair"
      };;
    esac
    # keccak256("get_dy(int128,int128,uint256)")
    get_dy_method_id=5e0d443f
    crv_dst_amount=$(setzer \
      --eth-call \
      "$crv_contract_addr" \
      "$get_dy_method_id" \
      "$crv_src_token$crv_dst_token$crv_src_amount"
    )
    case "${pair^^}" in
      WSTETHETH) {
        # wstETH is a non-rebasing wrapper that exposes the underlying stETH shares
        wsteth_contract_addr=7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        # keccak256("stEthPerToken()")
        steth_per_token_method_id=035faf82
        # how many stETH wei one would receive by unwarpping 10^18 wstETH wei
        steth_per_wsteth=$(setzer --eth-call "$wsteth_contract_addr" "$steth_per_token_method_id")
        # wstethEthPrice = stethPerWsteth * stethEthPrice
        price=$(bc -l <<<"ibase=16; (${steth_per_wsteth^^} * ${crv_dst_amount^^}) / (${crv_src_amount^^} * ${ten_to_18^^})")
      };;
      *) {
        price=$(bc -l <<<"ibase=16; ${crv_dst_amount^^} / ${crv_src_amount^^}")
      };;
    esac
    if [[ -n $price ]]; then
      setzer --format $price
    fi
  };;
  ddex) {
    json=$(curl -sS "${ORIGIN_DDEX_URL}/v4/markets/${base^^}-${quote^^}")
    setzer --format "$(jshon <<<"$json" -e data -e market -e lastPrice -u)"
  };;
  ftx) {
    json=$(curl -sS "${ORIGIN_FTX_URL}/api/markets/${base^^}/${quote^^}")
    setzer --format "$(jshon <<<"$json" -e result -e last -u)"
  };;
  fx) {
    json=$(curl -sS "${ORIGIN_FX_URL}/latest?base=${base^^}&access_key=${EXCHANGERATES_API_KEY}")
    setzer --format "$(jshon <<<"$json" -e rates -e "${quote^^}" -u)"
  };;
  gateio) {
    json=$(curl -sS "${ORIGIN_GATEIO_URL}/api/v4/spot/tickers?currency_pair=${base^^}_${quote^^}")
    setzer --format "$(jshon <<<"$json" -e 0 -e last -u)"
  };;
  gemini) {
    json=$(curl -sS "${ORIGIN_GEMINI_URL}/v1/pubticker/${base,,}${quote,,}")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  hitbtc) {
    json=$(curl -sS "${ORIGIN_HITBTC_URL}/api/2/public/ticker/${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  huobi) {
    json=$(curl -sS "${ORIGIN_HUOBI_URL}/market/detail/merged?symbol=${base,,}${quote,,}")
    setzer --format "$(jshon <<<"$json" -e tick -e bid -e 0)"
  };;
  kraken) {
    json=$(curl -sS "${ORIGIN_KRAKEN_URL}/0/public/Ticker?pair=${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e result -e "${base^^}${quote^^}" -e c -e 0 -u)"
  };;
  kucoin) {
    json=$(curl -sS "${ORIGIN_KUCOIN_URL}/api/v1/market/orderbook/level1?symbol=${base^^}-${quote^^}")
    setzer --format "$(jshon <<<"$json" -e data -e price -u)"
  };;
  kyber) {
    json=$(curl -sS "${ORIGIN_KYBER_URL}/change24h")
    setzer --format "$(jshon <<<"$json" -e "${quote^^}_${base^^}" -e rate_eth_now -u)"
  };;
  okex) {
    json=$(curl -sS "${ORIGIN_OKEX_URL}/api/spot/v3/instruments/${base^^}-${quote^^}/ticker")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  poloniex) {
    json=$(curl -sS "${ORIGIN_POLONIEX_URL}/public?command=returnTicker")
    setzer --format "$(jshon <<<"$json" -e "${quote^^}"_"${base^^}" -e last -u)"
  };;
  sushiswap) {
    case "${pair^^}" in
      SNXETH) {
        id="0xa1d7b2d891e3a1f9ef4bbc5be20630c2feb1c470"
        select="token1Price"
      };;
      CRVETH) {
        id="0x58dc5a51fe44589beb22e8ce67720b5bc5378009"
        select="token0Price"
      };;
    esac
    json=$(curl \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { pairs(where: { id: $id }) { token0Price token1Price } }", "variables": { "id": "'"$id"'" } }' \
      ${ORIGIN_THEGRAPH_URL}/subgraphs/name/zippoxer/sushiswap-subgraph-fork)
    setzer --format "$(jshon <<<"$json" -e data -e pairs -e 0 -e $select -u)"
  };;
  uniswap) {
    case "${pair^^}" in
      AAVEETH) {
        id="0xdfc14d2af169b0d36c4eff567ada9b2e0cae044f"
        select="token1Price"
      };;
      BALETH) {
        id="0xa70d458a4d9bc0e6571565faee18a48da5c0d593"
        select="token1Price"
      };;
      KNCETH) {
        id="0xf49c43ae0faf37217bdcb00df478cf793edd6687"
        select="token0Price"
      };;
      LRCETH) {
        id="0x8878df9e1a7c87dcbf6d3999d997f262c05d8c70"
        select="token1Price"
      };;
      PAXGETH) {
        id="0x9c4fe5ffd9a9fc5678cfbd93aa2d4fd684b67c4c"
        select="token1Price"
      };;
      SNXETH) {
        id="0x43ae24960e5534731fc831386c07755a2dc33d47"
        select="token1Price"
      };;
    esac
    json=$(curl \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { pairs(where: { id: $id }) { token0Price token1Price } }", "variables": { "id": "'"$id"'" } }' \
      ${ORIGIN_THEGRAPH_URL}/subgraphs/name/uniswap/uniswap-v2)
    setzer --format "$(jshon <<<"$json" -e data -e pairs -e 0 -e $select -u)"
  };;
  uniswap_v3) {
    case "${pair^^}" in
      COMPETH) {
        id="0xea4ba4ce14fdd287f380b55419b1c5b6c3f22ab6"
        select="token1Price"
      };;
      ETHUSDC) {
        id="0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
        select="token0Price"
      };;
      UNIETH) {
        id="0x1d42064fc4beb5f8aaf85f4617ae8b3b5b8bd801"
        select="token1Price"
      };;
      YFIETH) {
        id="0x04916039b1f59d9745bf6e0a21f191d1e0a84287"
        select="token1Price"
      };;
      CRVETH) {
        id="0x4c83a7f819a5c37d64b4c5a2f8238ea082fa1f4e"
        select="token0Price"
      };;
      WNXMETH) {
        id="0x058d79a4c6eb5b11d0248993ffa1faa168ddd3c0"
        select="token1Price"
      }
    esac
    json=$(curl \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { pools(where: { id: $id }) { token0Price token1Price } }", "variables": { "id": "'"$id"'" } }' \
      ${ORIGIN_THEGRAPH_URL}/subgraphs/name/uniswap/uniswap-v3)
    setzer --format "$(jshon <<<"$json" -e data -e pools -e 0 -e $select -u)"
  };;
  upbit) {
    json=$(curl -sS "${ORIGIN_UPBIT_URL}/v1/ticker?markets=${quote^^}-${base^^}")
    setzer --format "$(jshon <<<"$json" -e 0 -e trade_price)"
  };;
  *) {
    echo >&2 "Error: exchange not recognised: $src"
  };;
esac
