#!/usr/bin/env bash
set -e
pair=knceth
sources=(
  binance
  coinbase
  huobi
  kyber
  uniswap
  upbit
)

case $1 in
  binance|huobi) {
    knc_btc=$(setzer x-price "$1" knc:btc)
    eth_btc=$(setzer price ethbtc)
    setzer --format "$(bc -l <<<"$knc_btc / $eth_btc")"
  };;
  coinbase) {
    knc_usd=$(setzer x-price "$1" knc:usd)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$knc_usd / $eth_usd")"
  };;
  kyber) {
    setzer x-price "$1" knc:eth
  };;
  uniswap) {
    setzer x-price "$1" knceth
  };;
  upbit) {
    knc_krw=$(setzer x-price "$1" knc:krw)
    eth_krw=$(setzer x-price "$1" eth:krw)
    setzer --format "$(bc -l <<<"$knc_krw / $eth_krw")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
