#!/usr/bin/env bash
### included for backwards compatibility
set -e
[[ $# = 2 ]] || setzer --bad-usage "$0"

old=$1
new=$2

iszero=$(bc <<< "${old} == 0")

if [[ ${iszero} -eq 0 ]]; then
  swing=$(bc <<< "scale=10;(${new} - ${old}) / ${old} * 100")
  exec echo "$swing"
fi

echo 9999
