#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=OMGBTC")
omg_btc=$(jshon <<<"$json" -e price -u)
omg_btc=$(printf "%.10f" "$omg_btc")
btc_usd=$(setzer price eth)
bc -l <<<"$omg_btc * $btc_usd" | awk '{printf "%.10f", $0}'
