#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.okex.com/api/v1/ticker.do?symbol=mkr_btc")
mkr_btc=$(jshon <<<"$json" -e ticker -e last -u)
mkr_btc=$(printf "%.10f" "$mkr_btc")
btc_usd=$(setzer price btcusd)
bc -l <<<"$mkr_btc * $btc_usd" | awk '{printf "%.10f", $0}'