#!/usr/bin/env bash
set -e
pair=gntusd
sources=(
  binance
  bittrex
  coinbase
  poloniex
  upbit
)

case $1 in
  binance|bittrex) {
    gnt_btc=$(setzer x-price "$1" gntbtc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$gnt_btc * $btc_usd")"
  };;
  coinbase) {
    gnt_usdc=$(setzer x-price "$1" gnt:usdc)
    usdc_usd=$(setzer price usdcusd)
    setzer --format "$(bc -l <<<"$gnt_usdc * $usdc_usd")"
  };;
  poloniex) {
    gnt_btc=$(setzer x-price "$1" gntbtc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$gnt_btc * $btc_usd")"
  };;
  upbit) {
    gnt_krw=$(setzer x-price "$1" gntkrw)
    krw_usd=$(setzer x-price fx krwusd)
    setzer --format "$(bc -l <<<"$gnt_krw * $krw_usd")"
  };;
  *) {
    export SETZER_MIN_MEDIAN=2
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
