#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=REPBTC")
rep_btc=$(jshon <<<"$json" -e price -u)
rep_btc=$(printf "%.10f" "$rep_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$rep_btc * $btc_usd" | awk '{printf "%.10f", $0}'