#!/usr/bin/env bash
set -e
pair=wbtcusd
sources=(
  ddex
  kyber
)

case $1 in
  ddex) {
    wbtc_usdt=$(setzer x-price "$1" wbtc:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$wbtc_usdt * $usdt_usd")"
  };;
  kyber) {
    wbtc_eth=$(setzer x-price "$1" 0x2260fac5e5542a773aa44fbcfedf7c193bc2c599)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$wbtc_eth * $eth_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
