#!/usr/bin/env bash
set -e
pair=zrxusd
sources=(
  binance
  bitfinex
  coinbase
  okex
  upbit
)

case $1 in
  binance|okex) {
    zrx_btc=$(setzer x-price "$1" zrx:btc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$zrx_btc * $btc_usd")"
  };;
  bitfinex|coinbase) {
    setzer x-price "$1" zrx:usd
  };;
  upbit) {
    zrx_krw=$(setzer x-price "$1" zrx:krw)
    krw_usd=$(setzer x-price fx krwusd)
    setzer --format "$(bc -l <<<"$zrx_krw * $krw_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
