#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=BNBBTC")
bnb_btc=$(jshon <<<"$json" -e price -u)
bnb_btc=$(printf "%.10f" "$bnb_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$bnb_btc * $btc_usd" | awk '{printf "%.10f", $0}'