#!/usr/bin/env bash
set -e
pair=usdtusd
sources=(
  binance
  bitfinex
  huobi
  kraken
  okex
)

case $1 in
  binance|huobi|okex) {
    btc_usdt=$(setzer x-price "$1" btc:usdt)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$btc_usd / $btc_usdt")"
  };;
  bitfinex) {
    btc_usdt=$(setzer x-price "$1" btc:usd)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$btc_usd / $btc_usdt")"
  };;
  kraken) {
    setzer x-price kraken usdt:zusd
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
