#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=GNTBTC")
gnt_btc=$(jshon <<<"$json" -e price -u)
gnt_btc=$(printf "%.10f" "$gnt_btc")
btc_usd=$(setzer price btc)
bc -l <<<"$gnt_btc * $btc_usd" | awk '{printf "%.10f", $0}'