#!/usr/bin/env bash
set -e
json=$(curl -sS "https://api.kyber.network/buy_rate?id=0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2&qty=1.0")
num_eth=$(jshon <<<"$json" -e data -e 0 -e src_qty -e 0 -u)
num_mkr=$(jshon <<<"$json" -e data -e 0 -e dst_qty -e 0 -u)
eth_usd=$(setzer price ethusd)
bc -l <<<"$num_eth / $num_mkr * $eth_usd" | awk '{printf "%.10f", $0}'