#!/usr/bin/env bash
set -e
json=$(curl -sS "http://api.oasisdex.com/v1/markets/mkr/eth")
mkr_eth=$(jshon <<<"$json" -e data -e price -u)
mkr_eth=$(printf "%.10f" "$mkr_eth")
eth_usd=$(setzer price eth)
bc -l <<<"$mkr_eth * $eth_usd" | awk '{printf "%.10f", $0}'