#!/usr/bin/env bash
set -e
pair=batusd
sources=(
  binance
  bittrex
  coinbase
  upbit
)

case $1 in
  binance) {
    bat_btc=$(setzer x-price $1 batbtc)
    btc_usd=$(setzer price btcusd)
    setzer --format $(bc -l <<<"$bat_btc * $btc_usd")
  };;
  bittrex) {
    bat_btc=$(setzer x-price $1 btcbat)
    btc_usd=$(setzer price btcusd)
    setzer --format $(bc -l <<<"$bat_btc * $btc_usd")
  };;
  coinbase) {
    bat_usdc=$(setzer x-price $1 bat:usdc)
    usdc_usd=$(setzer price usdcusd)
    setzer --format $(bc -l <<<"$bat_usdc * $usdc_usd")
  };;
  upbit) {
    bat_krw=$(setzer x-price $1 batkrw)
    usd_krw=$(setzer x-price fx usdkrw)
    setzer --format $(bc -l <<<"$bat_krw / $usd_krw")
  };;
  ls) {
    for src in ${sources[@]}; do
      echo "$src: $(setzer price $pair $src)"
    done
  };;
  sources) {
    printf "%s\n" ${sources[@]}
  };;
  median|*) {
    export SETZER_MIN_MEDIAN=2
    setzer --median $pair ${sources[@]}
  };;
esac
