#!/usr/bin/env bash
set -e
pair=kncusd
sources=(
  ddex
  kyber
)

case $1 in
  ddex) {
    wbtc_usdt=$(setzer x-price "$1" wbtc:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$wbtc_usdt * $usdt_usd")"
  };;
  kyber) {
    knc_eth=$(setzer x-price "$1" 0xe41d2489571d322189246dafa5ebde1f4699f498)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$knc_eth * $eth_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
