#!/usr/bin/env bash
### setzer -- manipulate feeds
### Usage: setzer [<options>] <command> [<args>]
###    or: setzer <command> --help
###
### Manipulate feeds and update data
set -e

if [[ $2 = --help ]]; then
  exec "${0##*/}" help "$1"
elif [[ $1 = -* ]] && which "${0##*/}-$1" &>/dev/null; then
  exec "${0##*/}-$1" "${@:2}"
fi

"${0##*/}-${1-help}" "${@:2}"
