#!/usr/bin/env bash
set -e
pair=btcusd
sources=(
  binance
  bitfinex
  bitstamp
  coinbase
  gemini
  kraken
  upbit
)

case $1 in
  binance) {
    btc_usdt=$(setzer x-price $1 btcusdt)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format $(bc -l <<<"$btc_usdt * $usdt_usd")
  };;
  bitfinex) {
    btc_usdt=$(setzer x-price $1 btcusd)
    usdt_usd=$(setzer x-price cmc usdtusd)
    setzer --format $(bc -l <<<"$btc_usdt * $usdt_usd")
  };;
  bitstamp|coinbase|gemini) {
    setzer x-price $1 $pair
  };;
  kraken) {
    setzer x-price $1 xbtusd
  };;
  upbit) {
    btc_krw=$(setzer x-price $1 btckrw)
    usd_krw=$(setzer x-price fx usdkrw)
    setzer --format $(bc -l <<<"$btc_krw / $usd_krw")
  };;
  median|*) {
    echo $(setzer --median $pair 3 ${sources[@]})
  };;
esac
