#!/usr/bin/env bash
set -e
json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=LTCBTC")
bat_btc=$(jshon <<<"$json" -e price -u)
bat_btc=$(printf "%.10f" "$bat_btc")
btc_usd=$(setzer price btc)
bc <<<"$bat_btc * $btc_usd" | awk '{printf "%.10f", $0}'