#!/usr/bin/env bash
set -e
pair=dotusd
sources=(
  binance
  bitfinex
  huobi
  okex
  kraken
  kucoin
)

case $1 in
  kraken|bitfinex) {
    setzer x-price "$1" dot:usd
  };;
  huobi|binance|kucoin) {
    dot_usdt=$(setzer x-price "$1" dot:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l<<<"$dot_usdt * $usdt_usd")"
  };;
  okex) {
    dot_btc=$(setzer x-price "$1" dot:btc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$dot_btc * $btc_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
